### ISSUE TITLE
Add jqmd

### ISSUE THREAD

**Issue by pjeby** [fiatjaf/awesome-jq#17]
Hi there!  I'd like to propose adding [bashup/jqmd](/bashup/jqmd).  It's a "literate devops" tool that allows embedding shell, jq code, YAML, and JSON in a markdown document and making it executable.  (A bit like R markdown or IPython notebooks, except for shell/jq/YAML/JSON, and as a command-line tool rather than a GUI.)

I'd have submitted a PR, but wanted to confirm first that it would be considered both a command-line tool and arguably a language wrapper.  (At the same time, it seems like it's also in a third category that doesn't currently exist -- scripting tools?  Or should it go into use cases?) I'm also not sure how the ordering in the list works, it doesn't appear to be alphabetical or newest-entries-first?

Anyway, looking forward to your thoughts.

**Comment by fiatjaf** [comment]
Yes, this looks great. Categorizing is hard for this crazy thing, but I think would put it into "use cases". I am actually in search for something like this so I'll look into it more deeply later.

I don't know about the ordering. I think it's more like "things I remembered first go first", but you can put this one at the top because it's so cool!

Anyway, please open a pull request!
